{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
spec:
  replicas: {{ $svc.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $svc.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $svc.containerPort }}
          env:
            {{- if $svc.env }}
            {{- toYaml $svc.env | nindent 12 }}
            {{- end }}
{{- end }}
