apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fafnir.fullname" . }}-nats-init
  labels:
    {{- include "fafnir.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  nats.sh: |
    #!/bin/sh

    set -e

    nats stream add users \
        --subjects "users.>" \
        --storage file \
        --retention limits \
        --max-age 7d \
        --max-bytes 100MB \
        --defaults

    nats stream add orders \
        --subjects "orders.>" \
        --storage file \
        --retention limits \
        --max-age 7d \
        --max-bytes 100MB \
        --defaults

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fafnir.fullname" . }}-nats-init
  labels:
    {{- include "fafnir.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "fafnir.labels" . | nindent 8 }}
    spec:
      containers:
        - name: nats-init
          image: "natsio/nats-box:latest"
          command: ["/bin/sh", "/scripts/nats.sh"]
          env:
            - name: NATS_HOST
              value: "nats"
            - name: NATS_PORT
              value: "4222"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
        - name: scripts
          configMap:
            name: {{ include "fafnir.fullname" . }}-nats-init
