apiVersion: v1
kind: Service
metadata:
  name: security-service
  namespace: fafnir
  labels:
    app: security-service
spec:
  selector:
    app: security-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP