global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'security-service'
    static_configs:
      - targets: ['security-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'stock-service'
    static_configs:
      - targets: ['stock-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s